title: PLUGIN_ADMIN.SCHEDULER
form:
  validation: loose
  fields:
    tabs:
        type: tabs
        class: subtle

        fields:
            status_tab:
                type: tab
                title: Status

                fields:
                    setup_title:
                        type: section
                        title: PLUGIN_ADMIN.SCHEDULER_SETUP
                        underline: true

                    setup:
                        type: croninstall

                    status_title:
                        type: section
                        title: PLUGIN_ADMIN.SCHEDULER_STATUS
                        underline: true

                    status:
                        type: cronstatus

            custom_tab:
                type: tab
                title: Custom

                fields:
                    jobs_title:
                        type: section
                        title: PLUGIN_ADMIN.SCHEDULER_JOBS
                        underline: false
                    jobs:
                      type: list
                      style: vertical
                      label:
                      fields:
                        .id:
                          type: text
                          label: Name
                          placeholder: 'process-name'
                          validate:
                              required: true
                        .command:
                          type: text
                          label: Command
                          placeholder: 'cd ~;ls -lah;'
                          validate:
                              required: true
                        .args:
                          type: text
                          label: Extra Arguments
                        .at:
                          type: text
                          label: Run At
                          help: Cron formated "at" syntax
                          placeholder: '* * * * *'
                        .output:
                          type: text
                          label: Output File
                          help: The path/filename of the output file (from the root of the Grav installation)
                          placeholder: 'logs/ls-cron.out'
                        .output_mode:
                          type: select
                          label: Output Type
                          help: Either append to the same file each run, or overwrite the file with each run
                          default: append
                          options:
                              append: Append
                              overwrite: Overwrite
                        .email:
                            type: text
                            label: Email
                            help: Email to send output to. NOTE: requires output file to be set
                            placeholder: 'notifications@yoursite.com'




